import "./globals.css";
import { Cairo } from "next/font/google";
import { CartProvider } from "./context/CartContext";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800", "900"],
});

export const metadata = {
  title: {
    template: "%s | بن الباشا",
    default: "بن الباشا",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
